print("""````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                `.-::::-..```                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                    `````````..:ssyyyyysooo+/-.---..``                                                                                                                                                                                                              
                                                                                                                                                                                                                                                               `.-:::://+//:/osydmdhhhhyyyyhysosyysss+-``                                                                                                                                                                                                           
                                                                                                                                                                                                                                                  `````````  .:osooo++oydhyyhdddmmmmdddhhddddhyyhdhhmds+:.`                                                                                                                                                                                                         
                                                                                                                                                                                                                                              `.-/+++osso/:-:ohhhhdmmmmmNNNmmmmmmmdmmddddmmmmmmhhddhddyyyyo/.``                                                                                                                                                                                                     
                                                                                                                                                                                                                                            ./shdmmmmmmNNmmmddmmmmmmNNNmmmmNNmmmmmddmmmmmmmmNNNNmddhddhhdmdhyso+:.`                                                                                                                                                                                                 
                                                                                                                                                                                                                                          .:ydNNNNNNMNNNNMMNdhdmNNNNNNNmmmmmNNNmmmmmmmmmNNNNNNNNNNmdddhdmmmmmNmmh+.`                                                                                                                                                                                                
                                                                                                                                                                                                                                        `.ohmNNNMMMNNNNNNNNNmmNNMMMMMMNNNMMNMMMNNNNNNNNNNNNNNNNNNNNmmddmmNNNNNNNNmhs:.                                                                                                                                                                                              
                                                                                                                                                                                                                                     ``.:ohmNNMMMMMNmmmmmmNNNNNMMMMMMMNNNNMMMMMMMMMNNNNNNNNNNNNNNNNNNNmmNNNNNNMMMNNNds/-.`                                                                                                                                                                                          
                                                                                                                                                                                                                                    `.-+ydNNNNMMMNNNmmmmmmmmmmmNNNNNNNNNNNNMMMMMMMMMNNNNNNNNNNNNNNmNNNNNNNNNNNMMMMMMMNmdy+-`                                                                                                                                                                                        
                                                                                                                                                                                                                                   `-/+ydmmNNNNNNNNNNNNNNNNNNNNNNNNMMNNMMMMMMMMMMMMMMNNNNNNMNNMNNNNNMMNNNNNNNNMMMMMMMMMMNmhs+:.``                                                                                                                                                                                   
                                                                                                                                                                                                                                 `.:oyhdmdmmNNNNNNNNNMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNMMMMNNNNMNNNNMMMMMMMMNNmmdhyso/:.`                                                                                                                                                                               
                                                                                                                                                                                                                                .:oyhddddddmNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNMMNNNMMMMMMNNNNNNNmmmmddys/-`                                                                                                                                                                            
                                                                                                                                                                                                                              `./sddmddddmdmmNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNMMMMMMNNNNMNNNNNmmmmmdyo:`                                                                                                                                                                          
                                                                                                                                                                                                                             `-+yhmmmmmmNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNmmmmmmdho/:-.`                                                                                                                                                                     
                                                                                                                                                                                                                             `:ohmmmNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNmmmmmmmdys+:.                                                                                                                                                                  
                                                                                                                                                                                                                             ./sdNNNNNMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNMNNNNNNNNNNNNNNNds+/-`                                                                                                                                                              
                                                                                                                                                                                                                            `/ymNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMNNMMMNNNNNNNNNNNNNNmo-                                                                                                                                                             
                                                                                                                                                                                                                           .:sdNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNNMMNd:`                                                                                                                                                           
                                                                                                                                                                                                                        ``-+ydmNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNMMMMMMh:                                                                                                                                                           
                                                                                                                                                                                                                      `-+shdmmmNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNMMMMMMMMs`                                                                                                                                                          
                                                                                                                                                                                                                    .:sdmNNNmmNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNMMMMMMMMMMMMmo`                                                                                                                                                         
                                                                                                                                                                                                                  `:ymNMMMMNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmo.                                                                                                                                                        
                                                                                                                                                                                                                  :yNMMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm+`                                                                                                                                                       
                                                                                                                                                                                                                 `+mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd/`                                                                                                                                                      
                                                                                                                                                                                                                 `+mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNh+.`                                                                                                                                                    
                                                                                                                                                                                                                 `+dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdo.                                                                                                                                                    
                                                                                                                                                                                                                 `/dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNmmmmmddddmmmmNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNh:                                                                                                                                                    
                                                                                                                                                                                                                 `:hNMMMMMMMMMMMMMMMMMMMMMMNNNmmddhyysssooooooooosyhhhdmNNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNh:`                                                                                                                                                   
                                                                                                                                                                                                                 `/dMMMMMMMMMMMMMMMMMMMMNmddhysoo++//:::::::::::://++osyyddmmmddddhhhhhddmmNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmo-                                                                                                                                                    
                                                                                                                                                                                                                 .sNMMMMMMMMMMMMMMMMMMNmdhso+/::----...........----:://++ossssssssooooossyyhddmmNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNy:`                                                                                                                                                    
                                                                                                                                                                                                                `:hMMMMMMMMMMMMMMMMMMNdyo+/:-....`````````````......----:::://////////////+oossyyhhdddmmmNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNy-                                                                                                                                                     
                                                                                                                                                                                                                `+mMMMMMMMMMMMMMMMMMNds+/:-..```````````````````````..............--------:://///++oossyhhddmNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMms.                                                                                                                                                    
                                                                                                                                                                                                                .sNMMMMMMMMMMMMMMMMNds/:--.`````````````````````````````````````...........-----::://++ossyyhhddmmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm+`                                                                                                                                                   
                                                                                                                                                                                                                -hNMMMMMMMMMMMMMMMNds/--..`````````````````````````````````````````````..........----::/++oossyyhdmNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNs.                                                                                                                                                   
                                                                                                                                                                                                                :hMMMMMMMMMMMMMMMMmy+:-...``````````````````````````````````````````````````.......---::://++oosyydmmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNs.                                                                                                                                                   
                                                                                                                                                                                                                -yNMMMMMMMMMMMMMMNho/-...``````````````````````````````````````````````````````......---:::///+oosyhdmNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm/`                                                                                                                                                   
                                                                                                                                                                                                               `:hNMMMMMMMMMMMMMNds+:...`````````````` ```````````````````````````````````````........----::://+oosyhdmmNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNh-                                                                                                                                                    
                                                                                                                                                                                                               `/dMMMMMMMMMMMMMMNho/-.`````````````````````````````````````````````````````````.........---::///+oosyhddmNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNs.                                                                                                                                                    
                                                                                                                                                                                                               .omMMMMMMMMMMMMMNmy/-.``````````````````   ```````````````````````````````````````........---:://++oosyyhddmNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd/                                                                                                                                                     
                                                                                                                                                                                                               -yNMMMMMMMMMMMMNNdo:.`````````````````        ```````````````````````````````````````.....---::///++oossyhhdmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNy.                                                                                                                                                     
                                                                                                                                                                                                               :hNMMMMMMMMMMMMNmho-.`````````````````            ````````````````````````````````````....--:://///+++oosyyddmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd/`                                                                                                                                                     
                                                                                                                                                                                                               -hNMMMMMMMMMMMMNds+-.``````````````               ````````````````````````````````````....--:://///++++oosyhdmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNy.                                                                                                                                                      
                                                                                                                                                                                                               -yNMMMMMMMMMMMMmh+:..`````````                     ``````````````````````````````````....---:::///////++osyhdmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm+`                                                                                                                                                      
                                                                                                                                                                                                               .smMMMMMMMMMMMNdo:..``````                    ```````````````````````````````````````....---:::://////++osyhdmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMNy.                                                                                                                                                       
                                                                                                                                                                                                               .smMMMMMMMMMMMNs:..`````.....`.......````````````````````````````````````````````````....---:::::::///+oosyhdmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMd:                                                                                                                                                        
                                                                                                                                                                                                               .oNMMMMMMMMMMMd/.````..:ooo++++oooooooooo+/:--..``````````````````````````````````````....--:::::::://+ooyhdmNNMMMMMMMMMMMMMMMMMMMMMMMMMMMm+`                                                                                                                                                        
                                                                                                                                                                                                               `omMMMMMMMMMMNo-```.:+syhhhhhddmmmmmmNNmmmdhys+/:-...``````````...``````````````````````...----::::://+osyhdmNNMMMMMMMMMMMMMMMMMMMMMMMMMMNo.                                                                                                                                                         
                                                                                                                                                                                                               `/dMMMMMMMMMMh:```.+yddyssooosyhddmmNNNNmmmddhyso+/:--.......--:::////////::--.....``````.....--::::://+osydmNNMMMMMMMMMMMMMMMMMMMMMMMMMMy.                                                                                                                                                          
                                                                                                                                                                                                                .sNMMMMMMMMNs-```:syyo+/:::::::/+osyhhhdddddhhysso+/::--.-:/+ossyyyyyhhhdddhhsoo+//::-::::--..---:::://+osydNNMMMMMMMMMMMMMMMMMMMMMMMMMd:                                                                                                                                                           
                                                                                                                                                                                                                `/hNMMMMMMNy:````:oo/:--:///++++++++oossyyhyyyyyysoo+//:://+syyhhhddddmmmNNNNNNNmmdhhyyyyyys+:---:::////++oydNMMMMMMMMMMMMMMMMMMMMMMMMm/`                                                                                                                                                           
                                                                                                                                                                                                               ``./ohmNMNNd/.````:+/:-/+syyyhhhhhddddhhyyyyyhhhyyyso++///+osyhhhhddddddddmmmmmmmmmmmmmmmmmmdhs+/:::://////+oydNMMMMMMMMMMMMMMMMMMMMMMNs`                                                                                                                                                            
                                                                                                                                                                                                              .:/:--/yNMNNy:````.-/::/yhdmNmmmNNNNNNNNNmmdddhhhhhys+/:::/+osyhhddddhhhyyyyyyssssssssssyyhdmmNmds+//////////+ohNMMMMMMMMMMMMMMMMMMMMMMh-                                                                                                                                                             
                                                                                                                                                                                                             `-os+/::smMNd+.````..--:ohddmdyosdNNNNMMMNmmmmdddhhhs+:....-:/oyyhddddhhhhhhhhhhyyssoooooooosyhmNmdso/////////+oymMMMMMMMMMMMMMMMMMMMMMN+`                                                                                                                                                             
                                                                                                                                                                                                             `:oo+/:/smNNh:``````.--:+o++ossssyddmmmNmdhdmmmmdhhy+-``````.-/oyhdddddddmmmNmNNNNNNmmddhyysssshdmmhs+/////+///+smMMMMMMMMMMMMMMMMMMMMMh-                                                                                                                                                              
                                                                                                                                                                                                             `:++::-/ymNms-```````..-:/::/++ooosssyyyyyssyhhhhyo/.```` ```.:+shddhddddmmdsohNMMMMMMMNNmmdhysyhdddyo+///+////+sdNMMMMMMMMMMMMMMMMMMMm+`                                                                                                                                                              
                                                                                                                                                                                                             `:+/:--/yNNd+.``````````..-::////+++++ooooooooooo+:.`     ```.:/oyyyyhhhhhys+/odNNNNMMNmmNNNmdhyyyhhyso+///////+sdNMMMMMMMMMMMMMMMMMMMs.                                                                                                                                                               
                                                                                                                                                                                                             `-//---/ymNh/.``` ````````..-://++++ooooooo++++/:-``      ```.-/+sssoossssoooosyhhddmmdhhmmmmdhyyyyyyso++///////odNMMMMMMMMMMMMMMNNNNd:`                                                                                                                                                               
                                                                                                                                                                                                             `.::---:ommy:``````    ``````..--::::///::::---..`         `..-:/++o++++oooooooossssssyyyyyhhhhyyssoo++////////+sdNMMMMMMMMMNNmmdhyss+-                                                                                                                                                                
                                                                                                                                                                                                              `------odms-```````      ``````````...........``          ``..--:///////+++o++++++ooooooooooooo+++///::::::://+sdNMMMMMMMMNdhyyssyyss/.                                                                                                                                                               
                                                                                                                                                                                                              `.----:sddo-```              ``````````````````           ``.----:::::---::/+oooooooooo+++///::::::----::::://+ydNMMMMMMMNmhyyyhdddddy:`                                                                                                                                                              
                                                                                                                                                                                                              `..--:+hmh+.```                ``````````````             ``..---:::::--...--::///////::::--------------::::/+oymNMMMMMMNmdhyhhhhddddh/`                                                                                                                                                              
                                                                                                                                                                                                              ``..-:ohmh/.````                  `````````               ```..---:::--..............................----:::/+ohNMMMMMNNmddhhysssyhhhy-                                                                                                                                                               
                                                                                                                                                                                                              ``.-:/sdmy/.````               ```````````                ```....--:---.``````````````````````........---:::/+sdNMMMNmmdhyssoo++osyyho.                                                                                                                                                               
                                                                                                                                                                                                              ``.-:/sdmy:..`````````````````````.....``              `````...```.----.````````````````````````.......--:://+sdNMMNdddhys+++///+osss/`                                                                                                                                                               
                                                                                                                                                                                                               `..-:odmy/-..````````````````....--:-.....`````````````...---....`.----..```````````````````````.....--:://+oymMMNhosdmdyo+/////oso+-                                                                                                                                                                
                                                                                                                                                                                                               `...-+hmh+-....``````````....---:://:--:+so/.````.....--:/+++/:---.-----..`````````````````````....---::///+ohNMMms/+ymmhso++///+o+:`                                                                                                                                                                
                                                                                                                                                                                                               `...-/ymho:--......`......---::////::::+ydmho:......--:+shmmmdyo//::::::--...`````````````````....---::://+osdNMMmo:/smmdyso++//++/.                                                                                                                                                                 
                                                                                                                                                                                                               ``..-/ymdo/---..........--:://///::-.--/oyysso:-----:+sdNNNMMNmhso+++//::---..`````````````.....---:::://+oshmMMNh+:/sdmdyso+///+/-`                                                                                                                                                                 
                                                                                                                                                                                                                ```.:ydds/:------------::///++/:-....-::/++/++/:::/+shddhdddddyssso+//:::---.....`.`.........---:::////+oshmNMMms+/oydmdhys+//++-`                                                                                                                                                                  
                                                                                                                                                                                                                 ```.+hhs+/:---------::/+++++/////::/oooooooosoo+oosyhyyyyyyyyyyo++/::::::---..............---::::///++osydNMMMms+osyhddyso+/++:.                                                                                                                                                                   
                                                                                                                                                                                                                 ```.+hhyo+/:-----::://++o+ooosyyysyyhdddhyyhddddhhddhhhhhhyyyso/:::----::::-----.......----::::://+++osydmMMMNdo+ooosyyo///++/.                                                                                                                                                                    
                                                                                                                                                                                                                  ``./yysso+/:::::::///+oosyhddddhhhdhhdddddmNNNNmmNNNmmmmmmddhyo+/:-----:::::-------------:::////+++oyyhmNMNNmy+///////::/oo+-`                                                                                                                                                                    
                                                                                                                                                                                                                     ./ossoo//:::::////+sydmmmddhyyyyyyyhhddmNNNNmmNNMNNNmmmmmmddhyo+/:----::::--:::-----:::////++oosshddmNMNNds/::----:/+ss+-`                                                                                                                                                                     
                                                                                                                                                                                                                     `/sysso+/::::::///ohdmmmdhyysso+++++++osyyhdmdddmmmmmmmmmmmmmddhys+/:::::::::::::::::////+++osyyyhhhmNNNmh+:://+///+++:.`                                                                                                                                                                      
                                                                                                                                                                                                                     `/syyso++/::::://+shdmmdhhyysoo++o++///////+++//+osyyhhdddddmmmmmdhyo++//:::::::::::////++ossyhhhhddmNNNds/:--:///::-.`                                                                                                                                                                        
                                                                                                                                                                                                                     `:osyso++++//://:/+shmmmmdddddhhyyyyssyyssooooooooosssyyyyyyhhddmmmdhyss+/:::::////////++osyyhhhhdddmmNmho++/-.......`                                                                                                                                                                         
                                                                                                                                                                                                                     `-oyyssoooo/////::/+shdmmmmNNNNmmddhhhhhyyyyyhyyyyyyyhhhhhhhhddddmddhhhys/::::///////+++ossyhhhhhhddmmNmhyhhs+/::--.`                                                                                                                                                                          
                                                                                                                                                                                                                      .+yysysso+++++/:--/ohdhyssssssssssyyyhyyyyhhhhhhddmmmmmmmmmmmmmmmmddhhhs+:::://///+++oosyyhhhddddddmNNdydNNmdhyo:.                                                                                                                                                                            
                                                                                                                                                                                                                      `/yyyysooo+o++/:::/+yyyo+/:::::---::://+++ooooosyhhddmmNNNNNNNNNNmmdhhyo/:::://///++ooosyhhhhhddddmNNmdhmMMMNds:`                                                                                                                                                                             
                                                                                                                                                                                                                      `:shhyssssoo+++///+oyys+:----------------:::--::////+osyyhhddmmmmmmdhhyo/::://///++ooosyhhhhhhddddmmmmdhmMMMNh/`                                                                                                                                                                              
                                                                                                                                                                                                                       .+yhyssyso+ooo+++osso+/:----------::::::::---:::::///+++oossssyhdddhys+::://///+ooossyyhhhhhhhhddmmmddhmMMNmo-                                                                                                                                                                               
                                                                                                                                                                                                                       `-oyhyyyyssssssoosyys+/:-----:///++++oooo++++++////////////++++oshhhs+/:://++++osssyyyyyhhhhhhddmmmddhymMmy/.                                                                                                                                                                                
                                                                                                                                                                                                                        `:shhyyyyyhysyyyyhyyso/::://+osyhhhhdddhhhhhhysoo+//////://////oyhys+///+oosossyyyyyyyyhhdddddmmmmmdyymd+.                                                                                                                                                                                  
                                                                                                                                                                                                                         `/yhhyyyhhysyyyhhhhyso+//+ooosyyhhddddddddddhhyyysoooo+/:/:://oyhhysooooosssyyyyyhhhhhddddmmmmmmmdyoss:`                                                                                                                                                                                   
                                                                                                                                                                                                                          `/yhhyyhyyyyyhhhhhhyo++++ooossssyhhhdhhhhhhhhhhyysssso+/+///+oyhhyyyyysssyyyyyyyhhhhdmddmmmddmmds+//-                                                                                                                                                                                     
                                                                                                                                                                                                                           `:shyyhhhhdhddhhhhys+++o+++oooossyhhhhhhyyyyyyysyyooo++++++syhdhhhhhhhddhhhhhhhdddmmmmmmmmmmmds/::.                                                                                                                                                                                      
                                                                                                                                                                                                                            `:ohhhdddddddddhhys++++++////++oosyhhhhyyssooo+osoo+++oooyhdddddddddmmmddddddddmmmNNNNmmmmmmy+::-`                                                                                                                                                                                      
                                                                                                                                                                                                                             `:shhddddddhhdyssso++//::::::::/+oosssso++++/::////++syyhhdmmmmmmmmmmmmmmmmmmmmmNNNNNmmmmdy+:--.                                                                                                                                                                                       
                                                                                                                                                                                                                              `:shdmdddhhhhyyyso+/////:----::--://////:::::::://+oyyhhddmmmmmmmmmmNmmmmmNNNNNNNNNNNNNds+:-:-.                                                                                                                                                                                       
                                                                                                                                                                                                                                -ohdddddhdyyyssso++//++:-::::::::///:::::::///+++syyhddmmmmmNNNmNNNNNNNNNNNNNNNNNNNmho/::::-.                                                                                                                                                                                       
                                                                                                                                                                                                                                 `/ymmdddhhhyyssoo+++oo+//////////////////////+osyyhddmmmmmNNNNNNNNNNNNNNNNNNNNNNNdy+///:---`                                                                                                                                                                                       
                                                                                                                                                                                                                                  `:ydddddddhhysssssssso++oooooooo++++++++++++osyhdddddmmNNNNNNNNNNNNNNNNNNNMMNNmho+//:::---.                                                                                                                                                                                       
                                                                                                                                                                                                                                    -shdddddhhhyyyyyyyyyyssyyyssyssssssyyssssssyhdddmmmmNNNMNNNNNNNNNNNNNNNNNNdhyo+///::----.`                                                                                                                                                                                      
                                                                                                                                                                                                                                    `-+yhdddddhhhhhhhhhhhhhhhhhhhhhhhhhhhyyhhyyhdmmmmNNNMMMMNNNNMMMMNNMNNNNNmhys++/:::------.`                                                                                                                                                                                      
                                                                                                                                                                                                                                     `-/shhddddddhdhdddddddddddddddddhdddddhdddmmmNNNNNMMMNNNNMMMNMNNNNNNmdhyso+//::---------.`                                                                                                                                                                                     
                                                                                                                                                                                                                                     ``-/+syhdddddddddmdddmmdddmmmmmdmmmmmddmmmmmNNNNNNNNMNNNMNNNNNNNNmmdyso++//:::-------..-.``                                                                                                                                                                                    
                                                                                                                                                                                                                                      `..-:+syhhhdddddmmmmmmmmmmmmmmmmNNmmmmmmmmNNNNNNNNNMNNNNNNNNNmmdhyso+///:::::-------.....`                                                                                                                                                                                    
                                                                                                                                                                                                                                      ``...-:+osyhhdddddddmmmmmmmmmmmmNmmmmmmNNNNNNNNNNNMMMNNNNNNmdhyyso++////::::::------......``                   ```.----..``                                                                                                                                                   
                                                                                                                                                                                                                                      ``.....--/+ssyhdddddddddddddmmmmmmmmmNNNNNNNNNNNNNNNNNNNNmhyysso++//////::::::-----.........`              ``.-:/+oo+//+++/-....````                                                                                                                                          
                                                                                                                                                                                                                                       ```.....-:/++osyyhdddddddddddmmmmmmmNNNNNNNNNNNNNNNNmmdhyssoooo++/////:::::-------..---.....``        `.:/+++ooooo+///+++/::::::::-..``                                                                                                                                      
                                                                                                                                                                                                                                      ```````....--::/+osyhdddddddddmmmmmmmmmmmNNNNmmmmmmddhyyssooo++++//////:::::------------.......``    `-/sddhsoo+//////////::::///::::/::.`                                                                                                                                    
                                                                                                                                                                                                                                     ````````.....---::/+osyyyyhhhhhdddddddddddddddddhhhyyyssoooo++++////////:::::---------------.....`````./shhyo///////////+++++++oooooossoo+:`                                                                                                                                   
                                                                                                                                                                                                                                   ``.-.```.......----::///+ooooosssyyyyyyyyyyyyyyyyyssssssoooo++++/////////:::::---------------......`````.:/++/:::://////+oossssso+//:::------``                                                                                                                                  
                                                                                                                                                                                                                                  ``..:-````......------::///++++++oooooooooossssssssoooooo++++++++///////::::::::::::::---------.......--:/++++/////+ooo++//::---..............```                                                                                                                                 
                                                                                                                                                                                                                                ```..-/:.``.......-------::////+++++ooooooooooooooooooooo++++++++++/////:::::::::::::::::-----------:::::::://////++oo/::--...`...--::///////////:--.`                                                                                                                              
                                                                                                                                                                                                                              `.-....:+/```.......------:::://////++++++oooooooooo++++++++++++++++/////::::::::::::::::::-------:///////::://///+/:::-....----://+++///+oshmNNmmmdhys+:.`                                                                                                                           
                                                                                                                                                                                                                         ````````.-::+oo.```......------:::://////++++++++++++++++++++++++++++++////////////////:/:::::::--::/+//++///////+++/:--.......--:+shhs+:--....-:+ydmmmdhs+/::-.`                                                                                                                          
                                                                                                                                                                                                                        `........--::+ss-```....-------:::::://///++++++++++++++++++++++++++++++////////////////////::::::://:::::::://///:--........-:/oyyss+/-.........``..--....````````                                                                                                                         
                                                                                                                                                                                                                       `.---....---::+oy:````...--------::::://////++++++++++++++++++++++++++++++/////////////////////////:::--:::://::-...```...-:/oysso+:---...................```````````````                                                                                                                    
                                                                                                                                                                                                                      ``..---....---:/oy+.```.....------:::::///////////////++++++++++++++++++++++++////++///////////////::::://///:-.``````.-:/+oso/::----....---....................````````````                                                                                                                  
                                                                                                                                                                                                                     ````...---..-::/+oyo-```.......-----:::::::////////////////++++++++++++++++++++++++///////++/::-:::::::/::--...````.-:/+oo+/::----..-....----...........``````````````````````                                                                                                                 
                                                                                                                                                                                                                    `````...-::----:/+oys:...........-----:::::::::////////////////+++++++++++++++++//+++//+++++/:----::::---....```.-:/+ooo+/:--------...............................```````````````                                                                                                               
                                                                                                                                                                                                                  ````````..---::---/+shy/............-------:::::::::::////////////////////+++++++/////+++++//:---:::::--.``````.-/osyso/:----..--..............--:::::-::::----.......````````````````                                                                                                            
                                                                                                                                                                                                                  `````````....--/--:+ohh+-...........-----------::::::::::::://////////////////++//++++++//:---:://::-....``.-:+oyhyo/:--.............---::::///++++///::---.......`````````````````````                                                                                                           
                                                                                                                                                                                                              ```` ``````````...-::::/+yho--.........--------------:::::::::::::://///////////++++++++//:::---:/+/:-.```...-/syhhs+/:-..........---:://++ossssso++/:::-..........-------:::::::-----...````                                                                                                         
                                                                                                                                                                                                            `.--.````````````..-:://::/+yo:-.........--------------:::::::::::::://////////+++++++///::----::/+/:-.```.-/+syyys+/-....`...---:::/++osyyyysso+/::--......---::////:///:::::-...``.-://++//:-.``                                                                                                      
                                                                                                                                                                                                           `.--..````````````...-://:::/oo+:--.......----------:::::::::::::::////////////++++++/:-------:/++/-.````.:+ssso+:-.......--::/+osssyhhddhys+/:-.......-::/+oo++//:-..````              ``.-::////:-.``                                                                                                  
                                                                                                                                                                                                        ```..``  `.```````````....-:-://+oo+/:--......--------:::::::::::::://///////////////::--..-..-:/++/-```.-:/+o+/--.....--:/+ossyhhdddhhyyso+:-......-:/++ossss+:-.``                              ``..---..``                                                                                               
                                                                                                                                                                                                       `````       ```...`````.....---:---/++++/:-.....--------::::::::::::::::///::::::::::-......-:/++/-.``.-://:-....--:/+syhddmmmmdhso+/:---.....--:/+oyhhyo+/--.``                                          ``````                                                                                             
                                                                                                                                                                                                     ````            ``.........`.-::-----::///++/:------------::::::::::::::::::::---------.--..-:///:.```..--...`.-:+oyhdmmmdhyso+/:-......---:/+osysssyyys/-```                                                                                                                                                  
                                                                                                                                                                                                                        ``-/o/:--:hmmdyooosooo+++++++//::::::::::----::::::-------------:+oo+:-:/+++:-.``...``.-:+syhdhyso+/:--.......--:://osyhdmmNNNy-....`````                                                                                                                                                   
                                                                                                                                                                                                                         `./o+:--/dNMNdyoosssssoooosooo++/:::::--------::----------::/ohdNNNmyooo+//:::://////++oo++/:.```....--::/+oosssssyhdmmmmdhyo:``                                                                                                                                                           
                                                                                                                                                                                                                          `.---``/mMMd/-..`.....--://///:-----------::::::::::://////oymNNNMNmdhhyysssoo+:---.........-::/+oosyhhdddhyo/:://++o+/:--..`                                                                                                                                                             
                                                                                                                                                                                                                          `..`.`.sNMmy/::::--..`````...-------://++oossssyyyyyhhhhhhhmNNNNNNmhys+/:--..`````.--:://+osyhdddhsooo+++/-.``.----...```````                                                                                                                                                             
                                                                                                                                                                                                                         ```````:dMmsosyso/:.````````.--/+osyyyyysssooooossoo++///:/odNNNNmds+:-.....---:/+osyyssyyssyyso/:-.```````````..``````` ``  `                                                                                                                                                             
                                                                                                                                                                                                                         ```````omMy--/++/-.```````....--:/+ooo+//:-.....`````.....-omNNNNdhysoooosssyyyysoo+//:------..``````````````````````                                                                                                                                                                      
                                                                                                                                                                                                                         ``````-yNN+``.---.````````````..--::--:+oo//::://+++ooo+++shNNNNNmmmmmdhhyso+/:..``````````````````````````````````                                                                                                                                                                        
                                                                                                                                                                                                                         ```  `/dMN+````.````   ``````````.......:/+syhhyssoo++++oosdNNNNmhyso/:-.````````````````````````````````````````                                                                                                                                                                          
                                                                                                                                                                                                                        ````  `sNMN/```````      ```````   `````````.---:...```....:sNNNmo:.```````````````````` `````````````` `````                                                                                                                                                                               
                                                                                                                                                                                                                       ````   -hMMN:`````        `````````                    `  ``.omNNmo:..````````````       `````````      `                                                                                                                                                                                    
                                                                                                                                                                                                                        ``   `:dMMm- ``````` ````````````````          ````   `  ``.+mNNms:..```````````        ```````       ```                                                                                                                                                                                   
                                                                                                                                                                                                                             `omMMd-```````````````````````````````````````````````.+mNNms:..```````        `````````                                                                                                                                                                                               
                                                                                                                                                                                                                             .sNMMd-`````````       ````````````````````````````````:hNNms:.```` `          `````````                                                                                                                                                                                               
                                                                                                                                                                                                                             .hMMMh-`````````        ```````````````````````````````:yNNms:.```           `````````                                                                                                                                                                                                 
                                                                                                                                                                                                                             -dMMNs.`````````              `````````````````````````-smNms:.``             ```  ``                                                                                                                                                                                                  
                                                                                                                                                                                                                            `/mMMN/`````````                 ``````````````       ``.omNms:.`         ``                                                                                                                                                                                                            
                                                                                                                                                                                                                            `omMMd-``````                           ````            `/dNms:.``                                                                                                                                                                                                                      
                                                                                                                                                                                                                            .yNMMh.`````                                            `:hNms:.``````                                                                                                                                                                                                                  
                                                                                                                                                                                                                            -hNMMy.````                                              -yNms:.````````                                                                                                                                                                                                                
                                                                                                                                                                                                                            :dNMNs.```                                               .omms:.``````````                                                                                                                   `                                                                                          
                                                                                                                                                                                                                           `/dNMNo.```                                               `+mmy/..``                                                                                                                                                                                                                     
                                                                                                                                                                                                                           `/mNMN+.`                                                 `/dNh/..``                                                                                                                                                                                                                     
                                                                                                                                                                                                                           `omNMm/``                                                  -ymd+.``                                                                                                                                                                                                                      
                                                                                                                                                                                                                           .smMMd:`                                                   .ommo-```                                                                                                                                                                                                                     
                                                                                                                                                                                                                           .omNNh-                                                    `/hmy/.``                                                                                                                                                                                                                     
                                                                                                                                                                                                                            `---.                                                      `-:-`                                                                                                                                                                                                                        
""")